export const AllPossiblePlotFieldCommands = [
  "achievement",
  "ambient",
  "background",
  "call",
  "choice",
  "if",
  "condition",
  "cutscene",
  "effect",
  "getitem",
  "key",
  "move",
  "music",
  "name",
  "sound",
  "suit",
  "wait",
  "comment",
  "wardrobe",
  "status",
  "relation",
];

export const AllPossiblePlotFieldCommandsWithSayVariations = [
  "author",
  "hint",
  "notify",
  "character",
  "achievement",
  "ambient",
  "background",
  "call",
  "choice",
  "if",
  "condition",
  "cutscene",
  "effect",
  "getitem",
  "key",
  "move",
  "music",
  "name",
  "sound",
  "suit",
  "wait",
  "comment",
  "wardrobe",
  "status",
  "relation",
];

export const AllPossibleSayPlotFieldCommands = ["author", "hint", "notify"];
export const AllPossibleSayPlotFieldCommandsBlank = ["author", "hint", "notify", "character"];
